services:
  - type: web
    name: spotter-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn spotter.wsgi:application
    healthCheckPath: /
