# Generated by Django 6.0.2 on 2026-02-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trip',
            name='daily_logs_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='events_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_driving_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_duty_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used',
            field=models.FloatField(default=0, help_text='Hours already used in current 8-day cycle (0-70)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(help_text="Driver's current location", max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(help_text='Drop-off location', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(help_text='Pickup location', max_length=255),
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('driving', 'Driving'), ('rest', '10-Hour Rest'), ('break', '30-Minute Break'), ('fuel', 'Fuel Stop'), ('pickup', 'Pickup'), ('dropoff', 'Drop-off')], max_length=20)),
                ('start_time', models.FloatField(help_text='Hours from trip start')),
                ('duration', models.FloatField(help_text='Duration in hours')),
                ('description', models.TextField()),
                ('distance_at_event', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='routes.trip')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('off_duty_hours', models.FloatField(default=0)),
                ('sleeper_berth_hours', models.FloatField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_hours', models.FloatField(default=0)),
                ('activities', models.JSONField(default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='routes.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
