# Generated by Django 6.0.2 on 2026-02-20 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_trip_options_trip_daily_logs_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='remarks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='total_miles',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tripevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used',
            field=models.FloatField(default=0, help_text='Hours already used in current 8-day cycle (0-70)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
        migrations.AlterField(
            model_name='tripevent',
            name='event_type',
            field=models.CharField(choices=[('driving', 'Driving'), ('on_duty_not_driving', 'On Duty Not Driving'), ('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth')], max_length=30),
        ),
    ]
