# Generated by Django 6.0.2 on 2026-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_dailylog_remarks_dailylog_total_miles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cycle_hours_at_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_rest_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
